Initial commit, submission id: 20577352
NevMem/AVL-Tree pull request #1
Opened 2019-06-04 07:41 UTC by NevMem

2019-06-17 20:26 UTC, Skird requested changes

2019-06-17 20:26 UTC, Skird commented on avl.cpp
> +            auto current = new AVLNode<T>(v->value);
Опасность.
Увы, new **всегда** может бросить исключение и с этим ничего не поделать.
В целом, не ловить его - это нормально, но поскольку эта штука вызывается в конструкторе возможны красивые сценарии утечки: пользователь копирует структуру конструктором копирования, у него кончается память в процессе. Бросается exception, который он ловит, понимает, что памяти-то много, что-то там чистит и работает дальше. Но есть один нюанс: из конструктора было брошено исключение, поэтому деструктор вызван не будет (объект не сконструировался). Память утекла, потому что в рекурсии было много успешных вызовов new.
Дальше отметил опасные места.
Можно поиграть локально запуская процесс, после команды `ulimit -Sv 100000` (ML 100 Mb, правда не работает в сочетании с valgrind и asan по понятным причинам)

2019-06-17 20:26 UTC, Skird commented on avl.cpp
> +            root = recursive_copy_node_(other.root);
Опасность

2019-06-17 20:26 UTC, Skird commented on avl.cpp
> +                insert(*begin);
Опасность

2019-06-17 20:26 UTC, Skird commented on avl.cpp
> +template <typename T>
В целом реализация норм, мне понравилось, как будто много бойлерплейта, но сходу как лучше написать не знаю, поэтому сойдет.

2019-06-18 08:51 UTC, NevMem commented
Пофиксил, протестил, теперь в конструкторе от итераторов стоит try...catch, немного переделал рекурсивное копирование, просто поставить try...catch  в конструкторах нельзя поскольку из-за того что копируется вся структура дерева, в момент исключения дерево может быть не связно)

2019-06-26 08:46 UTC, Skird approved these changes
Да, теперь вроде корректно.
А вообще, всех проблем можно избежать с помощью `std::unique_ptr`, не знаю, почему *никто* в этом задании им не воспользовался.
Нередко гайдлайн такой, что сырой new вообще запрещен к использованию в коде и это правильно

2019-06-26 08:46 UTC, merged